import sys
sys.path.insert(0, "/home/hatch/workspace/stanford-frontier-ai/content/v2/cs336/scratch")
from plates import *

# ---- mup goal ----
p = Plate(960, 560); p.defs_arrow()
y = p.title("muP: one learning rate for all sizes", "Reparameterize so the optimal LR stops drifting with width. MiniCPM: minima all at 1e-2.")
p.panel(60, 140, 840, 180, "the recipe")
p.text(84, 190, "scale embeddings output; residuals by 1/sqrt(layers)", 15, INK)
p.text(84, 216, "init matrices by fan-in/fan-out ratio", 15, INK)
p.text(84, 242, "per-tensor learning rates; scale the LM head", 15, INK)
p.text(84, 280, "result: sweep LR across sizes, every minimum lands at 1e-2", 15, TEAL, 700)
p.panel(60, 350, 840, 140, "why it matters")
p.text(84, 400, "tune once on small models, deploy at 5x scale. No LR grid at the big run.", 15, INK, 600)
p.footer("Source: lecture MiniCPM slides, original plate. Shell 4: kill the drift.")
p.save("l11-mup.svg")

# ---- wsd ----
p = Plate(960, 540); p.defs_arrow()
y = p.title("WSD: the reusable schedule", "Warmup, stable, decay. Rewind to the stable phase and re-decay: no more restarts.")
p.panel(60, 140, 840, 200, "the trapezoid")
p.text(84, 190, "warmup: constant steps, horizon-independent", 15, INK)
p.text(84, 216, "stable: hold LR constant for most of the run", 15, INK)
p.text(84, 242, "decay: 10-20% of run, down to ~10% of max", 15, INK)
p.text(84, 280, "matches cosine; decay does the annealing work", 15, TEAL, 700)
p.panel(60, 370, 840, 100, "the payoff")
p.text(84, 414, "want a longer run? Roll back to stable, extend, re-decay. Chinchilla sweeps for 10% cost.", 15, INK, 600)
p.footer("Source: lecture WSD slides, original plate. Shell 4: schedules you can rewind.")
p.save("l11-wsd.svg")

# ---- two philosophies ----
p = Plate(960, 520); p.defs_arrow()
y = p.title("Stabilize or fit", "Two answers to drifting hyperparameters. Both work. Pick your religion.")
p.panel(60, 140, 400, 220, "stabilize: muP (MiniCPM)")
p.text(84, 190, "change the parameterization", 15, INK)
p.text(84, 216, "LR optimum stops moving", 15, TEAL, 700)
p.text(84, 250, "tune once, scale 5x", 14, MUT)
p.panel(500, 140, 400, 220, "fit: scaling laws (DeepSeek)")
p.text(524, 190, "grid LR x batch at scales", 15, INK)
p.text(524, 216, "fit the drift, extrapolate", 15, TEAL, 700)
p.text(524, 250, "batch up, LR down with compute", 14, MUT)
p.text(60, 400, "Qwen 2.5/3, Kimi: the fit recipe is now standard. muP is the invariance recipe.", 15, MUT)
p.footer("Source: lecture comparison, original plate. Shell 5: two philosophies, one problem.")
p.save("l11-two-philosophies.svg")

# ---- lr batch laws ----
p = Plate(960, 560); p.defs_arrow()
y = p.title("What the grids say", "Batch size follows the data. Learning rate falls with size, rises with data. Contours are smooth.")
p.panel(60, 140, 840, 140, "batch size")
p.text(84, 190, "depends only on D (tokens), not on N. Roughly sqrt(D) x const.", 16, INK, 600)
p.panel(60, 310, 840, 140, "learning rate")
p.text(84, 360, "down with model size N, up with data D. Under Chinchilla both move: LR falls with compute.", 16, INK, 600)
p.text(60, 480, "StepFun: high-res grids, smooth convex slices. Laws transfer to MoE at fixed active params.", 14, MUT)
p.footer("Source: lecture StepFun slides, original plate. Shell 4: read the contours.")
p.save("l11-lr-batch-laws.svg")

# ---- optimizer caution ----
p = Plate(960, 560); p.defs_arrow()
y = p.title("Small-scale wins can lie", "Muon crushed Adam on NanoGPT. At scale the gap shrank. Tune the baseline or the comparison is fiction.")
p.panel(60, 140, 840, 140, "two axes of scale")
p.text(84, 190, "compute (N and D coupled)  x  Chinchilla ratio (D/N)", 16, INK, 600)
p.text(84, 220, "an optimizer can win on one axis and lose on the other", 15, ORANGE, 700)
p.panel(60, 310, 840, 180, "Marin: beautiful scaling, then blowup")
p.text(84, 360, "great for orders of magnitude, then deviation, then divergence.", 15, INK)
p.text(84, 386, "fix: muP-style parameterization. Scaling trends are not promises.", 15, TEAL, 700)
p.footer("Source: lecture optimizer slides, original plate. Shell 5: distrust small wins.")
p.save("l11-optimizer-caution.svg")

# ---- muon ----
p = Plate(960, 560); p.defs_arrow()
y = p.title("Muon: orthogonalize the update", "Momentum, then Newton-Schultz: all singular values to 1. Matrix params only.")
p.panel(60, 140, 840, 200, "the algorithm")
p.text(84, 190, "B_t = mu * B_{t-1} + grad          (momentum)", 16, INK, 600)
p.text(84, 222, "B_t = U S V' -> U V'              (Newton-Schultz x5)", 16, INK, 600)
p.text(84, 254, "every direction becomes unit size: the spectral Adam", 15, TEAL, 700)
p.panel(60, 370, 840, 120, "the story")
p.text(84, 414, "NanoGPT speedrun: big win. Scaling studies: gap shrinks. Kimi K2: trained fully on Muon. Valid, verdict open.", 15, INK, 600)
p.footer("Source: lecture Muon slides, original plate. Shell 4: new optimizer, old skepticism.")
p.save("l11-muon.svg")

# ---- mup derivation ----
p = Plate(960, 600); p.defs_arrow()
y = p.title("muP from two invariants", "Activations O(1) at init. Feature learning O(1) per step. The rules drop out.")
p.panel(60, 140, 840, 120, "A1: activations at init stay O(1) in width")
p.text(84, 190, "solve sigma from the spectral norm: init ~ 1/sqrt(fan-in) x sqrt(fan-out/fan-in)", 15, INK, 600)
p.panel(60, 290, 840, 120, "A2: one gradient step changes activations by O(1)")
p.text(84, 340, "LR ~ fan-out / fan-in (SGD). Adam: 1 / fan-in. Per-layer learning rates.", 15, INK, 600)
p.panel(60, 440, 840, 100, "stress tests")
p.text(84, 484, "survives SwiGLU, RMSNorm. Breaks: learned RMSNorm gain, Lion, large decoupled weight decay.", 14, MUT)
p.footer("Source: lecture muP derivation, original plate. Shell 2: assert invariance, derive the rule.")
p.save("l11-mup-derivation.svg")

# ---- moe scaling ----
p = Plate(960, 540); p.defs_arrow()
y = p.title("MoE scaling is the new frontier", "Sparsity has a scaling law too. Kimi K2 picked 48: diminishing returns beyond.")
p.panel(60, 140, 840, 140, "what labs fit now")
p.text(84, 190, "Kimi K2: sparsity 48, sparser is better until it is not", 15, INK, 600)
p.text(84, 216, "Hunyuan: 96 tokens per active param at fixed sparsity", 15, INK, 600)
p.text(84, 242, "LLaMA3: IsoFLOP + loss-to-accuracy sigmoid", 14, MUT)
p.panel(60, 310, 840, 140, "MiniMax-01: architecture bake-off")
p.text(84, 360, "lightning vs hybrid vs softmax attention: comparable scaling, hybrid wins by decision", 15, INK, 600)
p.footer("Source: lecture survey, original plate. Shell 5: the frontier moved to MoE.")
p.save("l11-moe-scaling.svg")
